const path = require('path')
const fs = require('fs')
// Ensure TypeScript files required by @oclif/test are compiled at runtime
try {
    require('ts-node/register')
} catch {}
process.env.TS_NODE_PROJECT = path.resolve('tsconfig.json')
process.env.NODE_ENV = 'development'

// Remove development-only manifest during tests to avoid noisy warnings:
// - oclif.manifest.json is generated at publish/build time and can be stale in dev
// - oclif compares the embedded version to package.json and prints warnings on mismatch
// - those warnings go to stdout/stderr and break snapshot-based assertions
// - removing it in test runs is safe; the file is re-generated by our build/release scripts
const manifestPath = path.resolve('oclif.manifest.json')
if (fs.existsSync(manifestPath)) {
    try {
        fs.unlinkSync(manifestPath)
    } catch {}
}

global.oclif = global.oclif || {}
global.oclif.columns = 80
