# Cloudflare Worker configuration for DevCycle MCP Server
name = "devcycle-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-06-28"
compatibility_flags = ["nodejs_compat"]

# Production route
[[routes]]
pattern = "mcp.devcycle.com/*"
zone_name = "devcycle.com"

# Durable Objects configuration
[[migrations]]
new_sqlite_classes = ["DevCycleMCP"]
tag = "v1"

[[durable_objects.bindings]]
class_name = "DevCycleMCP"
name = "MCP_OBJECT"

# KV namespace for OAuth session storage
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "511f2abf74904876ba3e4627154f4d86"

# Environment variables
[vars]
NODE_ENV = "production"
API_BASE_URL = "https://api.devcycle.com"
AUTH0_DOMAIN = "auth.devcycle.com"
AUTH0_AUDIENCE = "https://api.devcycle.com/"
AUTH0_SCOPE = "openid profile email offline_access"
ENABLE_OUTPUT_SCHEMAS = "false"

# Secrets (set via: wrangler secret put <SECRET_NAME>)
# AUTH0_CLIENT_ID
# AUTH0_CLIENT_SECRET

# AI binding for future features (not currently used)
# [ai]
# binding = "AI"

# Observability
[observability]
enabled = true

# Development configuration
[dev]
port = 8787
local_protocol = "http"
