name: CLI Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: DevCycleHQ/release-action/gh-release@main
        with:
          draft: true
          prerelease: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
        run: npm publish --access public  
